SampleMicrosoftSite/SampleMicrosoftSite/Controllers/DetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleMicrosoftSite.Controllers
{
    public class DetailController : Controller
    {
        // GET: Detail
        public ActionResult Index()
        {
            return View();
        }
    }
}

SampleMicrosoftSite/SampleMicrosoftSite/Controllers/DeveloperToolsController.cs
using SampleMicrosoftSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleMicrosoftSite.Controllers
{
    public class DeveloperToolsController : Controller
    {
        // GET: DeveloperTools
        public ActionResult Index()
        {
            var developertoolscontroller = new List<DeveloperToolsModel>
            {
                new DeveloperToolsModel()
                {
                    Id = "visualstudio2022",
                    Name = "VIsual Studio 2022",
                    ReleasedDates = @"Released Date: ""November 8, 2021""",
                    Description = @"The most comprehensive IDE for .NET and C++ developers on Windows. Fully packed with a sweet array of tools and features to elevate and enhance every stage of software development.",
                    ImageUrl = "VS2022.png",
                    listOfDescription = "Visual Studio Community 2022",
                    listOfDescription2 = "Visual Studio Professional 2022",
                    listOfDescription3 = "Visual Studio Enterprise 2022",
                    DeveloperToolsImage = "VSInterface.jpg"
                    
                },
                new DeveloperToolsModel()
                {
                    Id = "visualstudio code",
                    Name = "Visual Studio Code",
                    ReleasedDates = @"Released Date: ""November 18, 2015""",
                    Description = @"A standalone source code editor that runs on Windows, macOS, and Linux. The top pick for JavaScript and web developers, with extensions to support just about any programming language.",
                    ImageUrl = "VScode.jpg",
                    listOfDescription = "Available on Windows",
                    listOfDescription2 = "Available on Mac",
                    listOfDescription3 = "Available on Linux",
                    DeveloperToolsImage = "VScodeInterface.jpg"
                },
                new DeveloperToolsModel()
                {
                    Id = "microsoft 365",
                    Name = "Microsoft 365",
                     ReleasedDates = @"Released Date: ""April 21, 2021""",
                    Description = @"Office 365 is now ""Microsoft 365"". Microsoft 365 is designed to help you achieve more with innovative apps, intelligent cloud services, and world-class security.",
                    ImageUrl = "Microsoft365logo.png",
                    listOfDescription = "For Home",
                    listOfDescription2 = "For Business",
                    listOfDescription3 = "For Enterprise",
                    listOfDescription4 = "For Education",
                    DeveloperToolsImage = "365Interface.jpg"
                }
            };
            return View(developertoolscontroller);
        }
    }
}

SampleMicrosoftSite/SampleMicrosoftSite/Controllers/HomeController.cs
using SampleMicrosoftSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleMicrosoftSite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(string id, string pageType)
        {
            var featuredPosts = new List<FeaturedViewModel>
            {
                new FeaturedViewModel()
                {
                    Id = "visualstudio 2022",
                    Header = "Developer Tools",
                    Title = "Visual Studio 2022",
                    PostedDate = DateTime.Now,
                    Description = @"The ""Visual Studio IDE"" is a creative launching pad that you can use to edit, debug, and build code, and then publish an app. Over and above the standard editor and debugger that most IDEs provide, Visual Studio includes compilers, code completion tools, graphical designers, and many more features to enhance the software development process.",
                    ImageUrl = "VS2022.png"
                },
                new FeaturedViewModel()
                {
                    Id = "visualstudio code",
                    Header = "Developer Tools",
                    Title = "Visual Studio Code",
                    PostedDate = DateTime.Now,
                    Description = @"The ""Visual Studio Code"" is a lightweight but powerful source code editor which runs on your desktop and is available for Windows, macOS and Linux. It comes with built-in support for JavaScript, TypeScript and Node.js and has a rich ecosystem of extensions for other languages and runtimes (such as C++, C#, Java, Python, PHP, Go, .NET).",
                    ImageUrl = "VScode.jpg"
                }
            };
            return View(featuredPosts);
        }
        public ActionResult About()
        {
            return View();
        }
        public ActionResult Privacy()
        {
            return View("Private");
        }
        public class MicrosoftController: Controller
        {
            public ActionResult Microsoft()
            {
                return View();
            }
        }

        
    }
}

SampleMicrosoftSite/SampleMicrosoftSite/Controllers/VideoController.cs
using SampleMicrosoftSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace SampleMicrosoftSite.Controllers
{
    public class VideoController : Controller
    {
        // GET: Video
        public ActionResult Index()
        {
            var videos = new List<VideoModel>()
            {
                new VideoModel()
                { 
                   Id = "visualstudio2022",
                   Name = "Visual Studio 2022",
                   ReleasedDates = @"Released Date: ""November 8, 2021""",
                   Description = @"The most comprehensive IDE for .NET and C++ developers on Windows. Fully packed with a sweet array of tools and features to elevate and enhance every stage of software development.",
                   VideoUrl = "https://www.youtube.com/embed/wu3BIeP1WD8",
                   TitleNameVideo = "VS22 - Feature Highlights",
                   VideoUrl2 = "https://www.youtube.com/embed/hZ1DASYd9rk",
                   TitleNameVideo2 = "VS Studio 2022 ASP.NetCore MVC Course"
                },
                new VideoModel()
                {
                    Id = "visualstudio code",
                    Name = "Visual Studio Code",
                    ReleasedDates = @"Released Date: ""November 18, 2015""",
                    Description = @"A standalone source code editor that runs on Windows, macOS, and Linux. The top pick for JavaScript and web developers, with extensions to support just about any programming language.",
                    VideoUrl = "https://www.youtube.com/embed/SYRwSyjD8oI",
                    TitleNameVideo = "VS Code - Setup and Basics",
                    VideoUrl2 = "https://www.youtube.com/embed/UTQp6mvhb0Y",
                    TitleNameVideo2= "Visual Studio Code Full Course"

                },
                new VideoModel()
                {
                    Id = "microsoft 365",
                    Name = "Microsoft 365",
                    ReleasedDates = @"Released Date: ""April 21, 2021""",
                    Description = @"Office 365 is now ""Microsoft 365"". Microsoft 365 is designed to help you achieve more with innovative apps, intelligent cloud services, and world-class security.",
                    VideoUrl = "https://www.youtube.com/embed/qKG8r1NERl4",
                    TitleNameVideo = "Introducing Windows 365",
                    VideoUrl2 = "https://www.youtube.com/embed/ySKjhmg9RRo",
                    TitleNameVideo2= "Microsoft 365 Basics Full Course"
                }
            };
     
            return View(videos);
        }
    }
}

SampleMicrosoftSite/SampleMicrosoftSite/Views/Home/About.cshtml
<div class="row">
    <div class="col-12">
        <nav>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="@Url.Action("Index", "Video")">Previous Page</a></li>
                <li class="breadcrumb-item active">About</li>
                <li class="breadcrumb-item"><a href="@Url.Action("Index","Privacy")">Next Page</a></li>
            </ul>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <h4>Microsoft Corporation is an American multinational technology corporation headquartered in Redmond, Washington. Microsoft's best-known software products are the Windows line of operating systems, the Microsoft 365 suite of productivity applications, and the Edge web browser. Its flagship hardware products are the Xbox video game consoles and the Microsoft Surface lineup of touchscreen personal computers. Microsoft ranked No. 14 in the 2022 Fortune 500 rankings of the largest United States corporations by total revenue; it was the world's largest software maker by revenue as of 2022. It is considered one of the Big Five American information technology companies, alongside Alphabet, Amazon, Apple, and Meta.</h4>
    </div>
</div>

SampleMicrosoftSite/SampleMicrosoftSite/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

SampleMicrosoftSite/SampleMicrosoftSite/Views/Home/Index.cshtml
@model IEnumerable<SampleMicrosoftSite.Models.FeaturedViewModel>
<div bgcolor="purple">

    <div class="row">
        <div class="col-12">
            <nav>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item active">Home</li>
                    <li class="breadcrumb-item"><a href="@Url.Action("Index","DeveloperTools")">Next Page</a></li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-6">
            <h1 class="display-4 fst-italic">Meet the Microsoft Family</h1>
            <p class="lead my-3"> Microsoft Corporation, leading developer of personal-computer software systems and applications. The company also publishes books and multimedia titles, produces its own line of hybrid tablet computers, offers e-mail services, and sells electronic game systems and computer peripherals.</p>
            <p class="lead mb-0"> <a href="#" class="text-black fw-bold">Read More...</a></p>
        </div>
        <div class="col-6">
            <img src="~/wwwroot/images/MicrosoftTools/Microsoftlogo.jpg" class="img-fluid rounded" />
        </div>
    </div>
    <hr />
    <div class="row mb-3 p-3">
        @foreach (var featured in Model)
        {
            <div class="col-6 p-3">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col" p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-primary">@featured.Header</strong>
                        <h4 class="mb-0">@featured.Title</h4>
                        <div class="mb-1 text-muted">@featured.PostedDate.ToString("MMMM dd, yyyy")</div>
                        <p class="card-text mb-auto" style="min-height: 150px; max-height: 150px; overflow-y: hidden">@featured.Description</p>
                        <a href="@Url.Action("Index","Detail", new {id = featured.Id})" class="stretched-link">Continue Reading...</a>
                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <img src="@Url.Content($"~/wwwroot/images/MicrosoftTools/{featured.ImageUrl}")" class="rounded" width="200" height="250" />
                    </div>
                </div>
            </div>
        }
    </div>

</div>

SampleMicrosoftSite/SampleMicrosoftSite/Views/Home/Private.cshtml
<div class="row">
    <div class="col-12">
        <nav>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                <li class="breadcrumb-item active">Privacy</li>
            </ul>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <h1>Privacy at Microsoft</h1>
    </div>
</div>